### ISSUE TITLE
add suport for unique sentinal values

### ISSUE THREAD

**Issue by mattsb42-aws** [awslabs/pipeformer#36]
There are places where it is useful to have a value that is unique without specifying an exact value.

There are two categories of sentinel here: sentinels that are persistently unique for all updates to a stack/set and sentinels that are unique per update.

One possible UX for this would be to use a similar syntax as we currently use for referencing inputs.

```yaml
pipeline:
  source:
    -
      ...
      outputs:
        - {ID:sourcecode}
  build:
    -
      ...
      inputs:
        - {ID:sourcecode}
  test:
    -
      ...
      inputs:
        - {ID:sourcecode}
    -
      ...
      inputs:
        - {ID:sourcecode}
```
---
Another thing to consider in this space is to reserve some sentinel IDs (such as `sourcecode`), and automatically add them as inputs and outputs to certain types of actions.
